### ISSUE TITLE
getinfo results in "Error: invalid argument"

### ISSUE THREAD

**Issue by Crypto2** [BitGo/bitgod#7]
Otherwise all RPC functions seem to work perfectly so far. This is a standalone bitgod without proxy enabled. Installed bitgod with npm.

2016-10-29T21:48:42.751Z - info: RPC call: getinfo  []
2016-10-29T21:48:42.754Z - error: Error: invalid argument
    at BitGo.estimateFee (/usr/lib/node_modules/bitgod/node_modules/bitgo/src/bitgo.js:1006:13)
    at BitGoD.handleEstimateFee (/usr/lib/node_modules/bitgod/src/bitgod.js:1286:21)
    at BitGoD.handleGetInfo (/usr/lib/node_modules/bitgod/src/bitgod.js:1466:24)
    at /usr/lib/node_modules/bitgod/src/bitgod.js:1550:21
From previous event:
    at null.<anonymous> (/usr/lib/node_modules/bitgod/src/bitgod.js:1549:16)
    at handleCall (/usr/lib/node_modules/bitgod/node_modules/json-rpc2/src/endpoint.js:69:18)
    at handle (/usr/lib/node_modules/bitgod/node_modules/json-rpc2/src/server.js:239:16)
    at IncomingMessage.requestEnd (/usr/lib/node_modules/bitgod/node_modules/json-rpc2/src/server.js:247:11)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
error: {"code":-32603,"message":"Error: invalid argument"}

**Comment by Crypto2** [comment]
It seems to be related to using settxconfirmtarget with bitcoin-cli, maybe it's not converting from a string to number before storing it? After using settxfee it works fine unless I do a settxconfirmtarget again.
